### ISSUE TITLE
Observation and execution modes for input window?

### ISSUE THREAD

**Issue by knicos** [EMGroup/js-eden#103]
An uncertain feature. Have different modes for the input window where you are either editing the script (default) or inspecting that script and how it relates to the environment. Another possible mode would be a step-by-step execution mode like some debuggers.

**Comment by ElizabethHudnott** [comment]
Inspecting mode sounds interesting.  Would be good to discuss ideas further (though not necessarily online, as I seem to have spent all day e-mailing you lol).  Debugger has been on Tim and I's desirability list for ages, though probably entails rewriting the JavaScript code generation, which is a dramatic step, but now the project is doing a new parser and a new language it makes sense.

**Comment by knicos** [comment]
Yes, to discuss in person. I'll write a comment here though: My new parser can directly execute each individual statement... it does this already when live editing so we basically have this support already I just need a UI for it.

**Comment by ElizabethHudnott** [comment]
*Bangs head*  Yes, of course it can!  Though is this working inside function calls, ranged scopes, and procedures though?  I'd be pleasantly amazed if the UI was the only thing.

**Comment by knicos** [comment]
Well UI isn't only thing if we want it to break when funcs/procs are called rather than just step through what is already in the input window. Right now I have to specifically make the input window execute a function as an entire block rather than as individual lines as it wants to. Even loops wouldn't be difficult since I have the abstract syntax tree to work with.

**Comment by ElizabethHudnott** [comment]
Cool. :D

**Comment by ElizabethHudnott** [comment]
Sounds like you've prepared a strong base from which to build on.

**Comment by knicos** [comment]
Observation mode works using "Inspect" button or alt key. There may be issues, but these come under a new issue here.
