### ISSUE TITLE
Multi-lingual UI

### ISSUE THREAD

**Issue by knicos** [EMGroup/js-eden#110]
Extract all UI strings into a language file ready for translation into other languages. This is partially done, but the plugins need to be trawled.

**Comment by knicos** [comment]
Minor note: meta info about plugins cannot currently be moved to a language file. This needs to be fixed somehow.

**Comment by ElizabethHudnott** [comment]
I'm happy to take on this task even though I know that I work slowly compared to you (and also have some other things on during the first few weeks of term).

**Comment by knicos** [comment]
Feel free, although I already have a framework in place for this in my branch along with some UI strings already moved out.
