### ISSUE TITLE
Difficulty in editing integer values 

### ISSUE THREAD

**Issue by meurigbeynon** [EMGroup/js-eden#151]
The live editing of numerical values by moving the mouse from side to side seems to work quite well. But it does sometimes seem that, although the arrow over the numerical value shows up readily, it is impossible to place the cursor between the digits in a value or use the arrow keys to navigate into the value. For instance in a definition such as 
x = 100;
placing the cursor after the semi-colon and trying to move left with the arrow key seems not to work.

Meurig

**Comment by knicos** [comment]
Worth adding that there is another related issue: if you put the cursor in the middle of a number (using arrow keys) and then try dragging, it will drag the value left of the cursor independently of the part on the right.... it's been split.

**Comment by knicos** [comment]
Would it be acceptable if number dragging was only possible in live mode? Editing in non-live could then be done more easily with the mouse.

**Comment by meurigbeynon** [comment]
I'd approve that - not sure that there's a lot of point in number dragging 
when it has no effect on anything else (cf. "making connections"). It's 
just rather macho.

**Comment by ElizabethHudnott** [comment]
Still doesn't solve the problem when the code is live though.  Must surely be possible to use a few Boolean variables to keep track of, "When the mouse button is released, was the mouse was moved by more than the threshold amount needed to initiate a change in numerical value (1 pixel?  More? Did the number change basically)?  If so then do nothing (already done a drag).  Otherwise it was a click so reposition the cursor.

**Comment by knicos** [comment]
Nope. Not that simple. jQuery already provides this for exactly that reason and I'm already doing it, however, when used in combination with a contenteditable div it seems to prevent the use of the contenteditable nature of the div underneath and there is nothing I can do. There might be a way if I were to manually implement the dragging and not use jquery... but not certain on that either.

**Comment by knicos** [comment]
Fixed to best of my current ability. You may have to click twice but it should work. The colour changes, this is a jQuery bug that has been fixed in newer versions of jQuery.... we should update.

**Comment by meurigbeynon** [comment]
By the way, belatedly, my experience of editing makes me more convinced 
that I'd rather not have this 'live editing' feature in operation unless 
the definition in question is being live edited. Is there a good reason to 
have it when there is no real-time feedback? Or am I missing something?

**Comment by knicos** [comment]
Only because an all or nothing implementation is simpler. No time before C6 to do this.
