### ISSUE TITLE
Lists  in worksheets

### ISSUE THREAD

**Issue by meurigbeynon** [EMGroup/js-eden#154]
If a bullet point in a list in the worksheet ends with a <jseden>...</jseden> tag, it seems to perturb the indentation of the next bullet point.

**Comment by ElizabethHudnott** [comment]
"... tag"?  What kind of tag is that?

**Comment by meurigbeynon** [comment]
A JSEDEN tag - seems as if spelling this out with angle brackets caused some problem in transmission!

**Comment by knicos** [comment]
I don't believe there is anything I can do about this? Putting some complexly styled item like an input window inside a list is inevitably going to mess up the flow. Better to just split the list and put the jseden tag in the middle.

**Comment by ElizabethHudnott** [comment]
I don't understand why this is a problem?  An < li > tag can contain arbitrarily complex div-s according to the spec.

http://www.w3.org/TR/html-markup/li.html

**Comment by knicos** [comment]
Then please explain to me what's happening because if that's true then this problem shouldn't exist. There is nothing about the jseden tag code that could do this if any div can be in there?

**Comment by knicos** [comment]
Found the problem. Not going to be able to fix it quickly because it requires much more sophisticated DOM manipulation.
