### ISSUE TITLE
Page observables not faithfully represented when accessed via Observable List

### ISSUE THREAD

**Issue by meurigbeynon** [EMGroup/js-eden#155]
Clicking on the name of a page observable in the Observable List should bring up a syntactically correct version of the definition for editing. But

page7 =
"</p>"
"This is a page"
"</p>"
;

loses crucial quotation marks when you double click on 'page7' in an Observable List.

**Comment by knicos** [comment]
the edencodeforvalue function needs updating to cope with the new parser. It assumes multi-line string support.

**Comment by ElizabethHudnott** [comment]
Confused.  Are there some missing backslashes in your example or something?

Another way of looking at it is the parser needs updating to support multiline strings, so that the return key means return, nothing more, nothing less.

**Comment by knicos** [comment]
Not happening. The changes required are very complex. I know the old parser did it but that did not have good error handling or syntax highlighting.

**Comment by knicos** [comment]
fixed by modifying edenCodeForValue instead of parser (for now at least).
