### ISSUE TITLE
Bug in _View_..._size proc

### ISSUE THREAD

**Issue by knicos** [EMGroup/js-eden#156]
Fails while triggering. This *might* be the cause of Meurigs broken input windows after a period of inactivity.... not sure about that but its the only error given.

In minified form!!!:

TypeError: b.size is undefined when triggering _View_input_size.

**Comment by knicos** [comment]
Not claiming this as an error in views, might be a bug in input window... I've fixed something that could be it. Do views call a "resize" function if there is one in viewdata?

**Comment by ElizabethHudnott** [comment]
Yes, they do.  Such a procedure is used to redraw canvases.
