### ISSUE TITLE
Make jseden tag attributes more robust

### ISSUE THREAD

**Issue by knicos** [EMGroup/js-eden#159]
Also add additional attributes and change the jseden tag to jseden-script to be standards compliant for eventual use of custom elements.

**Comment by ElizabethHudnott** [comment]
Custom elements?  Do you mean these kind of custom elements: https://w3c.github.io/webcomponents/spec/custom/ ?

**Comment by knicos** [comment]
yes. lol. pretty new stuff. Chrome seems to have it already :D
