### ISSUE TITLE
Project list to give agent name instead of run file

### ISSUE THREAD

**Issue by knicos** [EMGroup/js-eden#162]
Run files are no longer used directly to load projects, so an agent name is required to do the equivalent of `import projectname;`. Trivial change, I could do this in master if you like? Otherwise, instead of including run file do:

```
Eden.Agent.importAgent("agentpath/name/here", [], function (agent) {});
```

where `[]` is an options list that can contain: "noexec", "create", "remote", "local", "rebase", "force"....

**Comment by ElizabethHudnott** [comment]
Don't mind who does it, but am working on the project list atm.
