### ISSUE TITLE
Introducing blank lines when you copy a line 

### ISSUE THREAD

**Issue by meurigbeynon** [EMGroup/js-eden#170]
When replicating definitions such as the following, a common approach is to make several copies of the definition and edit the occurrences of a key index (in this case 1 in the context of floor1) to make the new instances. 

overfloor1butt is (mouseX>floor1button.boxbx) && (mouseX<floor1button.boxbx+20) && (mouseY>floor1button.boxby) &&( mouseY<floor1button.boxby+20);

At present, if you copy this definition and paste it in such a way that you expect to get the same definition replicated on the line below, the editor introduces a blank line between the defn and the copy. This means that when you go through editing the instances of the key index in the definitions you can't do this by ranging the cursor down a column of chars at a time, relying on the editor to remember your place in the definition to avoid having to manually locate occurrences of the key index. Until other ways of editing are available, this makes replication of definition much less efficient.

Is there a good reason why a blank line gets to be introduced?.

**Comment by knicos** [comment]
I don't get blank lines when I do this and have used this technique extensively. ???

**Comment by knicos** [comment]
I can't reproduce this. Did this text originally get copied into the script view from an external editor? Just wondering if it might be a line endings issue. Also, which browser?

**Comment by meurigbeynon** [comment]
The browser is Firefox. I don't think the script came in from an external 
editor - I'm doing much less of that (in the spirit of the new 
environment) and typically have been copying the other way to preserve 
stuff. I hadn't appreciated the issue about the cursor - tend to 
mistakenly think of the cursor and teh mouse as one and the same (!).

I must see if it's something quirky about the way I copy lines and see if 
I can *avoid* getting a newline.

**Comment by ElizabethHudnott** [comment]
I noticed extra blank lines sometimes being inserted too but couldn't figure out the steps needed to reproduce the problem.  I was using Chrome.
