### ISSUE TITLE
Occasional erratic behaviour in the Inspect feature 

### ISSUE THREAD

**Issue by meurigbeynon** [EMGroup/js-eden#171]
I have been using the Inspect feature to look at the values of observables in this group of definitons:
:
floor1buttonlight is Circle(floor1button.boxbx+10,floor1button.boxby+10, 7, "yellow" if floor1buttsel else "grey", "grey"); 
floor2buttonlight is Circle(floor2button.boxbx+10,floor2button.boxby+10, 7, "yellow" if floor2buttsel else "grey", "grey"); 
floor3buttonlight is Circle(floor3button.boxbx+10,floor3button.boxby+10, 7, "yellow" if floor3buttsel else "grey", "grey"); 
floor4buttonlight is Circle(floor4button.boxbx+10,floor4button.boxby+10, 7, "yellow" if floor4buttsel else "grey", "grey"); 
floor5buttonlight is Circle(floor5button.boxbx+10,floor5button.boxby+10, 7, "yellow" if floor5buttsel else "grey", "grey"); 

They all seem to work fine except  for the observable floor5buttsel. Inspect has been selecting substrings rather than the whole identifier name and displaying results such as @@ or @sel.

**Comment by meurigbeynon** [comment]
This issue seems to have had something to do with the status of the observable floor5buttsel at the time - it was undefined, but apparently behaving as if true in the definition of the observable

floor5buttonlight 

There were similar anomalies with other undefined observables, but when .floor5buttsel was set to false all these anomalies seem to go away, so that e.g. .floor4buttsel is still undefined but floor4buttonlight is now grey, when it was formerly yellow.

**Comment by knicos** [comment]
Is this by chance caused by trying to inspect an observable that currently has the cursor on it? In other words was the text cursor within the word "floor5buttsel" when you went into inspect mode? The result of inspecting an observable like that is that it is split by the cursor... same issue as with number dragging.

**Comment by knicos** [comment]
Assuming its the cursor problem, this is fixed.
