### ISSUE TITLE
Sign in with Twitter doesn't seem to work?

### ISSUE THREAD

**Issue by cssbz** [EMGroup/js-eden#180]
I'm using Chrome 47.0.2526.80 (64-bit) on a Mac running 10.11.1.

When I click on "Sign in with Twitter", I see a progress indicator in Chrome briefly, but the window content remains the same: I see no error messages or indication of success.

![image](https://cloud.githubusercontent.com/assets/945402/11722867/45cf8d1e-9f63-11e5-937d-e2c8c5352fce.png)

The behaviour seems the same whether I'm logged in to Twitter or not.

**Comment by knicos** [comment]
Thanks! I'll fix this right now

**Comment by cssbz** [comment]
Yup, that seems to have fixed it, thanks :)

![image](https://cloud.githubusercontent.com/assets/945402/11723800/1562af44-9f68-11e5-8993-031eda342d91.png)
