### ISSUE TITLE
Environment never completes loading in Safari 9?

### ISSUE THREAD

**Issue by cssbz** [EMGroup/js-eden#181]
I've tried using Safari 9.0.1 on a Mac running 10.11.1, loading the page <http://jseden.dcs.warwick.ac.uk/construit.c6/>

I left it loading for 5+ minutes, but it seemed to stick at the state shown in this screenshot (the circular progress indicator keeps animating, but I see no other progress):

![image](https://cloud.githubusercontent.com/assets/945402/11723241/4012af4e-9f65-11e5-9ed4-5cbdfba47644.png)

**Comment by knicos** [comment]
Using an online test site with Safari 5.1 on Windows Vista... it does not support ECMAScript6 generator functions and therefore we cannot, at this time, support Safari.

**Comment by cssbz** [comment]
OK... I'd like to suggest adding a list of supported browsers on that loading screen, to make that a bit clearer.  Perhaps change "Loading..." to "Loading... (supported browsers include Chrome and Firefox)"?

**Comment by knicos** [comment]
Done, displays browser version message if not supported
