### ISSUE TITLE
Alt+I Inspect path click

### ISSUE THREAD

**Issue by knicos** [EMGroup/js-eden#186]
Alt+I inspect mode doesn't allow path clicking, even though the button does.

**Comment by knicos** [comment]
suggestion to change this to holding down Ctrl? Does this conflict with anything?

**Comment by knicos** [comment]
Can't reproduce this in Chrome on Linux, it works.

**Comment by ElizabethHudnott** [comment]
Ctrl+i opens the bookmarks side bar in Firefox and IE.

Why do you suggest switching to the control key?  I suggest we stick to the alt key for most of our shortcuts and leave the ctrl key free for browsers' own use (except where we're implementing a strongly established convention, ctrl+x, ctrl+enter, etc.)

**Comment by knicos** [comment]
Alt+I is alternative to original just Alt. Plan is to make it just Ctrl instead.
