### ISSUE TITLE
Ability to jump to definition from a reference

### ISSUE THREAD

**Issue by cssbz** [EMGroup/js-eden#188]
Say I have the following definition shown within the Input window, as part of a longer script:

picture is [hello];

I'd like to be able to select and then modifier-click the "hello" text, and be taken to the definition of "hello".

Xcode has a feature like this (for Objective-C etc): for example, if if I hold the cmd key down and move the mouse over text like "[self updateTimeOfLastChartUpdate];", then the formatting of the  "updateTimeOfLastChartUpdate" text is given a blue underline, and clicking on it takes my editor window to the definition of that method.  When the method is one I've defined in my code, it takes me to that definition... if the method is eg a system API, it takes me to the relevant line in the header file.

I've discussed this briefly with Elizabeth, who has mentioned some potential difficulties here: eg if the definition is in another file, if the name is defined via backticks...

Also a brief discussion with Nick: I'd like to see the original definition in the context where I wrote it... I tend to remember things spatially (eg I'll remember that I read a particular fact on the right hand page of a book, about a third down...) and so the original organisation of the text is important.

**Comment by knicos** [comment]
This is basically supported internally by providing agent name and line number (which is dynamic), main requirement now is deciding on key shortcut and having a means of activating an agent tab and jumping to the already known line number.

**Comment by ElizabethHudnott** [comment]
The key combination to jump to the definition of an identifier should be the same as the key combination to jump to an agent by clicking on its path in an import statement (since both involve linking to a new editor location) and the key should be the Cmd key key on Mac and the Ctrl key on other platforms (to be consistent with other applications).  There is also however the inspection mode where clicking on an identifier reveals its current value.  This needs to be assigned a different key combination (or none at all).

**Comment by knicos** [comment]
Done. Use Ctrl + click on import paths or observable names. Ctrl+click on observables should now take you to the tab/agent and line where it is defined. Note this only works for observables defined with "is" and it may also not work in various other situations where the location cannot be determined.

Please test before I close this.

**Comment by knicos** [comment]
ps. the relevant line is not highlighted as this requires a feature in #197.
