### ISSUE TITLE
Ctrl (or Alt?) + clicking on an import statement no longer works

### ISSUE THREAD

**Issue by ElizabethHudnott** [EMGroup/js-eden#192]
Tested in Chrome 46.0.2490.86 m on WIndows 8.1.

A while back, holding down the control key (or was it alt?) and clicking on the agent reference part of an import statement opened the agent's script in another tab.  This no longer works (with either key).  Although the inspect mode offers similar functionality, it's handy to be able to open a tab quickly without enabling inspect mode.

Would be good to have this feature back.  Other applications, such as web browsers, Microsoft Word and Notepad++ use the convention of Ctrl + clicking a hyperlink to perform a secondary action, so it's a natural(ish) thing to want to do.  I say "-ish" because currently the lines are not underlined to indicate that they are links (as is the convention), so you have to have some kind of "insider knowledge".  Alternatively, GMail and Google Docs have an alternative way of handling the edit vs open ambiguity associated with hyperlinks, which I think is a better approach (for those applications anyway), but more complicated.

**Comment by knicos** [comment]
Because the feature was removed and replaced with Alt+I as mentioned in another issue. Reason: it was causing problems with some users when it was just the Alt key. Suggestion is hold down Ctrl, again as mentioned in issue #186
