### ISSUE TITLE
input agent sometimes fails to initialize

### ISSUE THREAD

**Issue by ElizabethHudnott** [EMGroup/js-eden#193]
Chrome on WIndows 8.1, Project Manager not logged in.

Meta undefined for view/script/input/configEden.Agent @ wrappers.js:33createCommon @ interpreter.js:813createDialog @ interpreter.js:2182EdenUI.createView @ plugins.js:103(anonymous function) @ VM61055:6(anonymous function) @ VM61148:1Eden.AST.FunctionCall.execute @ ast.js:1725Eden.AST.Script.executeGenerator @ ast.js:2503runEdenAction @ ast.js:2518Eden.AST.Script.executeReal @ ast.js:2483Eden.AST.Script.execute @ ast.js:2555Eden.AST.If.execute @ ast.js:1604Eden.AST.Script.executeGenerator @ ast.js:2503runEdenAction @ ast.js:2518(anonymous function) @ ast.js:2539finish @ wrappers.js:183(anonymous function) @ wrappers.js:522(anonymous function) @ database.js:574l @ jquery-1.8.3.min.js:2c.fireWith @ jquery-1.8.3.min.js:2T @ jquery-1.8.3.min.js:2r @ jquery-1.8.3.min.js:2
wrappers.js:149 Importing: view/script/input@default

**Comment by knicos** [comment]
The error pasted is not relevant to the issue. The actual problem has to do with async connection to project manager. Did you use construit.c6 version or emgroup.github (master) because an async loading issue was fixed yesterday morning.

**Comment by ElizabethHudnott** [comment]
It happened last night.  Would have either been construit.c6 or my local copy (having pulled first), but not sure which.  Will keep an eye out to see if it happens again.

**Comment by knicos** [comment]
I think it still happens but very rarely and may be related to needing a cache clear.
