### ISSUE TITLE
Show "Play" in gutter when hovering on entire line

### ISSUE THREAD

**Issue by knicos** [EMGroup/js-eden#197]
To make gutter execution more obvious. Also make the play icon more visible.

**Comment by knicos** [comment]
Working on this, but should we attempt to indicate lines that have changes which have not yet been executed? Should the "play" icon be changed to something more obvious?

**Comment by ElizabethHudnott** [comment]
> should we attempt to indicate lines that have changes which have not yet been executed?

Yes, please.  I think that would be useful.
