### ISSUE TITLE
Embedded JavaScript no longer executed in root JavaScript scope

### ISSUE THREAD

**Issue by ElizabethHudnott** [EMGroup/js-eden#199]
Failing test case.

${{
	var Foo = function () {
		this.x = 2;
	}

}}$;

x = ${{ new Foo() }}$;

**Comment by ElizabethHudnott** [comment]
Don't think this ever worked.

**Comment by knicos** [comment]
Use encapsulation, for example put Foo inside Eden, EdenUI, eden or edenUI ... Also, the system makes extensive (and in the future even more so) use of the fact that embedded javascript does NOT execute in the root JavaScript scope. I have taken advantage of the semantics of "eval" which is where this comes from.

**Comment by knicos** [comment]
It never will be
