### ISSUE TITLE
Strange Gutter Bug

### ISSUE THREAD

**Issue by ElizabethHudnott** [EMGroup/js-eden#200]
Steps to reproduce:
1) Open c6/menace/complete from the agent list
2) Run Force
3) All gutter functionality stops working
4) Make a change to the code.
5) Use Ctrl+z to undo the change (Sometimes this works, sometimes Ctrl+z is not responsive at this point.  If it doesn't work then click on the undo button)
6) The gutter works normally again.

**Comment by knicos** [comment]
Gutter is being entirely rewritten for #197 and so should be much more resilient which is likely to fix this issue also.
