### ISSUE TITLE
Numbers at start of agent names

### ISSUE THREAD

**Issue by jonnyf** [EMGroup/js-eden#201]
Apparently we allow agent names to be uploaded with a number at the start (e.g. "jc/dynamics/1DPOM"), but the import statement generates an error (i.e., "import jc/dynamics/1DPOM"). Presumably we don't want to allow agents with a number at the start of the sub-path? If so we should make sure this is discouraged in the interface.

**Comment by knicos** [comment]
It now checks and prevents numbers in sub paths
