### ISSUE TITLE
JS-EDEN Doesn't load in Internet Explorer 11

### ISSUE THREAD

**Issue by ElizabethHudnott** [EMGroup/js-eden#206]
From http://jseden.dcs.warwick.ac.uk/nick/index-dev.html

SCRIPT1005: Expected '('
File: ast.js, Line: 2597, Column: 54
BOOTSCRIPT: import lib;
${{ doneLoading(); }}$;

followed by the following error, repeated many times:

XML5619: Incorrect document syntax. Line: 1, Column 1

and then:

SCRIPT28: Out of stack space
File: translator.js, Line: 876, Column: 9

then a few more XML5619 errors, then:

SCRIPT445: Object doesn't support this action
File: translator2.js, Line: 2450, Column: 2

**Comment by knicos** [comment]
IE 11 does not support ECMAScript 6 Generator functions and so we cannot support IE 11

**Comment by knicos** [comment]
Version checks now display warning for IE 11
