### ISSUE TITLE
Switch Statement Not Working

### ISSUE THREAD

**Issue by ElizabethHudnott** [EMGroup/js-eden#207]
Executing the following action produces an error message instead of the expected result.

x = "A";

action test {
	y = @;
	switch (x) {
	case "A":
		 y = "Success, branch 1.";
		break;
	case "B":
		y = "Success, branch 2.";
		break;
	default:
		y = "Success, default branch.";
	}
}

**Comment by knicos** [comment]
Not implemented in parser. This was due to my desire to move away from funcs and procs anyway so it became a low priority.
