### ISSUE TITLE
Append not escaping quotes properly

### ISSUE THREAD

**Issue by jonnyf** [EMGroup/js-eden#208]
When writing a walkthrough the following does not work:
append _view_input_script,"b = \"Hello\";";
the result is that the input window is populated with:
b = \"Hello\"
so the backslash is not unescaped.

**Comment by knicos** [comment]
i doubt this is just an append problem and how have we not noticed this before? I have no laptop atm, but this fix is simple in js/core/lex.js parseString function.

**Comment by jonnyf** [comment]
Actually, we think it might be only for append - so probably not something we'd have spotted before:

a = "Hello \"there\"";
writeln(a);

works fine - a is just:
Hello "there"
without the extra backslashes. So maybe it's just the append function that this affects?
