### ISSUE TITLE
Mutable values should be copied to prevent modification to shared data

### ISSUE THREAD

**Issue by itsmonktastic** [EMGroup/js-eden#32]
E.g. right now

```
x = y = [1, 2, 3];
x[1] = 4;
```

In JS-Eden `x` and `y` refer to the same array, but in tkeden the modification to `x` isn't seen in `y`, they are totally separate values. The latter is the ideal behaviour when using dependency and agency, e.g.

```
x = [1, 2, 3];
y is x;
proc p : y { writeln("y changed"); }
```

Modifying `x` will silently cause changes to `y`, but `p` will not see the change because it was due to aliasing, not dependency or agency.

**Comment by knicos** [comment]
As a note: this was solved by always copying values. This is a pointless copy if the value is a generated one anyway, so the new parser does a copy only when required.
