### ISSUE TITLE
Forgotten symbols persisting in the symbol list, observable list, etc

### ISSUE THREAD

**Issue by ElizabethHudnott** [EMGroup/js-eden#54]
Steps to reproduce:

Declare, say for example:

x = 2;

Then bring up either a symbol list view or an observable list view and find x in the list.

Then issue the statement:

forget("x");

Notice that after executing the above statement x remains listed in the symbol list (or observable list) even though x no longer exists in the symbol table.

If you then subsequently refresh the symbol list by altering the regular expression specifying the symbols to search for then x disappears from view and will not appear again (unless x is subsequently redefined).

**Comment by knicos** [comment]
It goes undefined. I consider this a won't fix issue.
