### ISSUE TITLE
Pressing Ctrl+m brings the error window up

### ISSUE THREAD

**Issue by jonnyf** [EMGroup/js-eden#62]
Even if the error window has been closed, it can be refocused by pressing Ctrl+m.

**Comment by ElizabethHudnott** [comment]
What's Ctrl+m supposed to to do?  Is this a feature coded into JS-EDEN?  jQuery?  The browser?  Linux?

**Comment by jonnyf** [comment]
It's something Tim added to allow cycling through the windows. It's JS-Eden specific.

**Comment by ElizabethHudnott** [comment]
Fixed.  Though does anybody know about this feature other than you, Tim and me?  M stands for?
