### ISSUE TITLE
Inability to use include inside procs and funcs

### ISSUE THREAD

**Issue by ElizabethHudnott** [EMGroup/js-eden#69]
Reported by Anthony Harfield.

I have a relatively simple trigger on a button:

func loadDataButtonPressed : loadDataButton_clicked {
   include("models/heartrate/testdata.jse");
}

But when I accept this into the input window, I get the error:
Unexpected token ';'. Expected ')' to end a argument list.

If I change the include line for something else (e.g. hello = 1;) then there is no error.

I tried a few other things, but I think there is a problem parsing an include inside any proc. For example:

proc testInclude {
   hello = 1;
}

Vs.

proc testInclude {
   hello = 1;
   include("test");
}

First one is ok, the second one does not parse.

**Comment by knicos** [comment]
may as well close this? New parser doesn't have this issue.
