### ISSUE TITLE
SymbolFramer/Mined Observables/ObservableMine Uses Inconsistent Naming

### ISSUE THREAD

**Issue by ElizabethHudnott** [EMGroup/js-eden#70]
Since the spring time we have had a naming policy in place with regards to naming plug-ins and views.

1) The name registered under EdenUI.plugins should be same as the name displayed in the Plug-in Manager (with hyphens and spaces removed).  This makes it easier to write scripts that load plug-ins programmatically.  E.g. a plug-in listed as "Xxx Yyy" in the Plug-in Manager should be loadable using require("XxxYyy") without needing to know any separate internal plug-in name.
Exception: established EM acronyms such as "ADM".

2)  Similarly, the internal name for a view type should be the same as the name displayed in the New Window menu, with any spaces, hyphens or trailing "Window" suffix removed.  This is so that views can easily be created programmatically using createView(name, type).

Question: Is the phrase "Symbol Framer" supposed to represent some wider/reuseable concept beyond the observable mining stuff?  If so then maybe consider describing the wider concept in the plug-in's description field?

I don't know if it's possible (for further consistency) to rename the folders and files containing the source code too without breaking the version history and/or reeking havoc with any uncommented or unpushed changes elsewhere, but many of the plug-in source code files now no longer have names that match the revised plug-in names.  It would be good to update the directory structure if we can do this easily.  At least in the case of the symbol framer nobody apart from Nick has yet worked on it yet.

**Comment by knicos** [comment]
Renaming of files, folders, the plugin are all ok but we need to choose a name. I've used both Symbol Framer and Observable Mine because I don't know what to call it. To be decided.

Is there a way for me to modify the style of a view window if I don't know it's div id or parent?
