### ISSUE TITLE
Multi-line strings supported by highlighter

### ISSUE THREAD

**Issue by knicos** [EMGroup/js-eden#82]
Multiple lines in a string break syntax highlighting and error line counting.

**Comment by knicos** [comment]
Supported but with quotes around each line. Unlikely to improve this further.

**Comment by ElizabethHudnott** [comment]
You said that multiline quotes could be done if a different quote character were used. Could bring back the <% %> syntax that I implemented in the old parser.  Multiline strings plus the advantage of being able to copy and paste text from other sources (e.g. paste quotations into paragraphs) without getting errors for failing to escape double quotes.

**Comment by knicos** [comment]
Yes, this is a possibility. I'll add this as a new issue though because it refers to a different feature and not the support of quote based multi-line.
