### ISSUE TITLE
Add "in" and "step" options to range scoping

### ISSUE THREAD

**Issue by knicos** [EMGroup/js-eden#83]
Allow an observable to range over all values in a given list instead of just over an integer range. Also allow ranges to be incremented by different steps, including floating point steps. Will involve the introduction of new keywords and should if possible follow standard conventions.

**Comment by ElizabethHudnott** [comment]
...including negative steps (in order to get the values arranged in the opposite direction to the indexes).

**Comment by knicos** [comment]
Done
