### ISSUE TITLE
Button to un-embed script from page

### ISSUE THREAD

**Issue by knicos** [EMGroup/js-eden#85]

**Comment by knicos** [comment]
removed button. Is there any need for this?

**Comment by ElizabethHudnott** [comment]
Meurig specifically asked for this feature but he seldom finds material on GitHub without some guidance.  I'll draw his attention to this issue by sending him an e-mail link.

I'm not entirely sure what Meurig's reasons for his request were, as we've not discussed it in depth, but I believe they centre around going seamlessly back and forth between "authoring" and "doing" the worksheet and wanting to have something that you're working on continuously visible while still being free to scroll the page.

On possibly the same / possibly a different but related issue, when Meurig and I were exploring the environment together last Wednesday it became apparent that sometimes a convenient way of resizing a canvas or an input window is needed.  I suspect this may also be part of the motivation for wanting to un-embed too.  I think a nice useability improvement would be if the embedded views could be resized with the mouse without un-embedding them, similar to how Chrome allows users to resize text boxes in web pages.

**Comment by knicos** [comment]
I fully intend to add such things to Canvas, but scripts can just be copied into a new window. Although resizing would probably be a good idea.

**Comment by knicos** [comment]
Not required. Can now resize embedded scripts. Can also show tabs and drag to window as a quick undock.
