### ISSUE TITLE
Auto comment out lines that are not current

### ISSUE THREAD

**Issue by knicos** [EMGroup/js-eden#91]
In live script input windows, automatically comment out any lines that no longer correspond to the current definition of that observable/function/procedure.

Problems with previous implementation: too many notifications, changes and re-highlights, especially when pasting large blocks of code and powering on.

**Comment by ElizabethHudnott** [comment]
And a keyboard shortcut for quickly uncommenting them to make them the current ones again?  Would be good to have some kind of visual indicator to be able to find them quickly among a large script and easily distinguish them visually when scrolling from other comments.  Maybe a slightly different background colour for these lines? Sorry to be a pain in the arse, having previously objected that the pop-up messages and the the warning triangle icons were too obvious and "in your face" and interrupted the flow of work too much, I'm now complaining that commenting on it's own is perhaps too subtle...

**Comment by knicos** [comment]
No worries, it's an important point. I was intending to have a little info icon next to those lines which can also be used to find out why it became commented out.

**Comment by ElizabethHudnott** [comment]
Yay.  Friendly info icons sound good :)  Better than, "Warning, you've entered a nuclear area.  EDEN is having a meltdown." :P

**Comment by knicos** [comment]
No longer desired
